using System.Collections;
using System.Collections.Generic;
using UnityEngine;
public enum GameSoundTag
{
    NONE,
    SFX_DRIP,
    SFX_THROW,
    SFX_LAND_LEAF,
    SFX_WALK_GRASS,
    SFX_WALK_GROUND,
    SFX_PUSH_STONE,
    SFX_CRACK_CRUMBLE,
    SFX_CRACK_FILL,
    SFX_FALL_HOLE,
    SFX_CUT,
    SFX_TREE_CUT,
    SFX_HI5_JINGLE,
    SFX_HI5_CLAP,
    SFX_ROOM_COMPLETE_JINGLE,
    SFX_ROOM_INCOMPLETE_JINGLE,
    SFX_JUMP,
    SFX_LAND,
    SFX_CALL,
    SFX_CRYING,
    SFX_QUAKE,
    SFX_LARGE_QUAKE,
    SFX_BIRD_WINGS,
    SFX_BIRD_GULL1,
    SFX_BIRD_GULL2,
    SFX_BIRD_GULL3,
    SFX_BIRD_GULL4,

}
